[package]
name = "async-bus-macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.49"
proc-macro-error = "1.0.4"
quote = "1.0.23"
syn = { version = "1.0.107", features = ["extra-traits", "full"] }

[dev-dependencies]
trybuild = "1.0.73"
